[package]
name = "three-osc"
version = "0.0.0"
authors = ["Adam Godwin <evilspamalt@gmail.com>"]
license = "GPL-3.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2 = "0.6.0"
wmidi = "3.1.0"#wmidi = "4.0.6"
fastrand = "1.7.0"
itertools = "0.10.3"